CONTEXT_VQA = [
    {
        "question": "What are the men looking at?",
        "candidate": "The men are looking at a presentation or diagram on a whiteboard.",
        "reference": "tv",
        "vote": 1,
    },
    {
        "question": "Is this a wet sport?",
        "candidate": "No, kite flying is not a wet sport. It is a recreational activity that involves flying a kite, typically using a string or line to control the kite's movement in the air. In the image, a woman is flying",
        "reference": "no",
        "vote": 5,
    },
    {
        "question": "What is this device used for?",
        "candidate": "This device, which appears to be a stainless steel oven, is used for cooking food. It has a silver and black color scheme and is equipped with a digital clock, allowing users to keep track of cooking times and ensure that",
        "reference": "cooking",
        "vote": 5,
    },
    {
        "question": "How many boats are sailing on the water?",
        "candidate": "a few",
        "reference": "1",
        "vote": 1,
    },
    {
        "question": "How many boats are sailing on the water?",
        "candidate": "There are three boats sailing on the water.",
        "reference": "1",
        "vote": 1,
    },
    {
        "question": "What kind of fuel does this van use?",
        "candidate": "The van uses propane as its fuel source.",
        "reference": "biodiesel",
        "vote": 1,
    },
    {
        "question": "What kind of fuel does this van use?",
        "candidate": "diesel",
        "reference": "biodiesel",
        "vote": 4,
    },
    {
        "question": "What color is the grass?",
        "candidate": "The grass is green in the image.",
        "reference": "green",
        "vote": 5,
    },
    {"question": "What color is the horse?", "candidate": "grey", "reference": "black", "vote": 1},
    {
        "question": "What color is the horse?",
        "candidate": "The horse is gray and black.",
        "reference": "black",
        "vote": 3,
    },
    {
        "question": "What is the number of the bus?",
        "candidate": "london london london london london london london l",
        "reference": "15",
        "vote": 1,
    },
    {
        "question": "Are the men wearing shirts?",
        "candidate": "No, the men in the image are not wearing shirts. They are shirtless.",
        "reference": "no",
        "vote": 5,
    },
    {
        "question": "What website is on the phone's screen?",
        "candidate": "yelp",
        "reference": "google",
        "vote": 1,
    },
    {
        "question": "Where is the catcher?",
        "candidate": "behind the home plate",
        "reference": "behind batter",
        "vote": 1,
    },
    {
        "question": "Where is the catcher?",
        "candidate": "The catcher is positioned behind the batter, ready to catch the ball.",
        "reference": "behind batter",
        "vote": 5,
    },
    {
        "question": "How many people are represented by the feet shown in the photo?",
        "candidate": "The feet in the photo represent two people, as there are two tennis rackets on the ground near them.",
        "reference": "4",
        "vote": 1,
    },
    {
        "question": "What country's flag is represented on the sandwich?",
        "candidate": "The sandwich is topped with the US flag, which represents American patriotism.",
        "reference": "usa",
        "vote": 5,
    },
    {
        "question": "What country's flag is represented on the sandwich?",
        "candidate": "the united states",
        "reference": "usa",
        "vote": 5,
    },
    {
        "question": "What is covering the bottom half of the tall building featured in this picture?",
        "candidate": "The bottom half of the tall building in the image is covered with trees.",
        "reference": "trees",
        "vote": 5,
    },
    {
        "question": "What is covering the bottom half of the tall building featured in this picture?",
        "candidate": "a tarp covering the bottom half of the tall building featured in this picture",
        "reference": "trees",
        "vote": 1,
    },
    {
        "question": "Is the floor tile?",
        "candidate": "Yes, the floor tile is described as being blue.",
        "reference": "no",
        "vote": 1,
    },
    {"question": "Is the floor tile?", "candidate": "yes", "reference": "no", "vote": 1},
    {
        "question": "What is the color of the steering wheel?",
        "candidate": "white",
        "reference": "red",
        "vote": 1,
    },
    {
        "question": "What are the men sitting on?",
        "candidate": "couches",
        "reference": "couch",
        "vote": 5,
    },
    {
        "question": "How many different flowers are in the vase?",
        "candidate": "There are many different flowers in the vase, but I cannot provide an exact number without more specific information.",
        "reference": "8",
        "vote": 2,
    },
    {
        "question": "What color is the shower curtain?",
        "candidate": "The shower curtain in the bathroom is blue.",
        "reference": "blue",
        "vote": 5,
    },
    {
        "question": "What color is the vase?",
        "candidate": "The vase is blue.",
        "reference": "blue",
        "vote": 5,
    },
    {
        "question": "Are the trees covered in snow?",
        "candidate": "Yes, the trees in the image are covered in snow, indicating that it is a winter scene.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "What is the man trying to hit?",
        "candidate": "The man is trying to hit a tennis ball with his tennis racket.",
        "reference": "tennis ball",
        "vote": 5,
    },
    {
        "question": "Is this a giraffe?",
        "candidate": "Yes, the image shows a giraffe walking on a rocky surface.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "What could the black dish be used for?",
        "candidate": "The black dish could be used for various purposes, such as holding cutlery, serving food or snacks, or even as a decorative element in the kitchen. In the image, the black dish is placed near the kitchen sink, which",
        "reference": "cooking",
        "vote": 1,
    },
    {
        "question": "What could the black dish be used for?",
        "candidate": "utensils",
        "reference": "cooking",
        "vote": 1,
    },
    {
        "question": "Is there a lot of alcohol in this photo?",
        "candidate": "Yes, there is a lot of alcohol in this photo. The image shows a blurry scene with a stop sign and people standing around, and it appears to be taken at a bar.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "Are there cars on the street?",
        "candidate": "Yes, there are cars on the street, and they are driving by a bus stop where people are standing.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "Is this man wearing tennis shoes?",
        "candidate": "Yes, the man in the image is wearing tennis shoes while holding a baseball bat.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "What shape is the rice dish?",
        "candidate": "square",
        "reference": "round",
        "vote": 1,
    },
    {
        "question": "What shape is the rice dish?",
        "candidate": "The rice dish is shaped like a bird.",
        "reference": "round",
        "vote": 1,
    },
    {
        "question": "Is it cold outside?",
        "candidate": "Yes, it is cold outside, and the person is dressed warmly to handle the chilly weather while skiing.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "What type of walling and flooring is it?",
        "candidate": "tiled walling and flooring",
        "reference": "tile",
        "vote": 5,
    },
    {
        "question": "What is in the mug?",
        "candidate": "The mug contains Pepsi, which is a sugary soft drink.",
        "reference": "pepsi",
        "vote": 5,
    },
    {
        "question": "What is the bus' destination?",
        "candidate": "hyderabad, uttar pradesh",
        "reference": "hyde park",
        "vote": 1,
    },
    {
        "question": "How many umbrella's are in the picture?",
        "candidate": "There are two umbrellas in the picture.",
        "reference": "2",
        "vote": 5,
    },
    {
        "question": "What type of vehicle are the people riding?",
        "candidate": "The people are riding motorcycles.",
        "reference": "motorcycle",
        "vote": 5,
    },
    {
        "question": "How many seats at the white table?",
        "candidate": "There are two seats at the white table.",
        "reference": "8",
        "vote": 1,
    },
    {
        "question": "How many seats at the white table?",
        "candidate": "four",
        "reference": "8",
        "vote": 1,
    },
    {
        "question": "Is it raining in this photo?",
        "candidate": "Yes, it is raining in the photo, and the girl riding the horse is using an umbrella to shield herself from the rain.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "What color is the man's hat?",
        "candidate": "The man's hat is black.",
        "reference": "black",
        "vote": 5,
    },
    {
        "question": "Where was this picture taken?",
        "candidate": "This picture was taken at a park, where a group of people is standing on a grassy hill.",
        "reference": "park",
        "vote": 5,
    },
    {
        "question": "Where was this picture taken?",
        "candidate": "in california",
        "reference": "park",
        "vote": 1,
    },
    {
        "question": "Are there any people using the ski lift?",
        "candidate": "Yes, there are people using the ski lift in the image.",
        "reference": "yes",
        "vote": 5,
    },
    {"question": "How many people are inside cars?", "candidate": "0", "reference": "6", "vote": 1},
    {
        "question": "How many people are inside cars?",
        "candidate": "There are two people inside a car in the image.",
        "reference": "6",
        "vote": 1,
    },
    {
        "question": "Is the truck a fire truck?",
        "candidate": "Yes, the truck in the image is a fire truck.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "Is this an apartment or a cabin?",
        "candidate": "This is a cabin, as it is described as having a cozy and rustic atmosphere with a stone fireplace and wooden interior.",
        "reference": "cabin",
        "vote": 5,
    },
    {
        "question": "Where is the knife?",
        "candidate": "The knife is on the table, near the plate of food.",
        "reference": "on plate",
        "vote": 3,
    },
    {
        "question": "Is he standing up or stooping down?",
        "candidate": "The man is stooping down in the ocean while holding a surfboard.",
        "reference": "stooping down",
        "vote": 5,
    },
    {
        "question": "What is this device?",
        "candidate": "a refrigerator",
        "reference": "fridge",
        "vote": 5,
    },
    {
        "question": "What is this device?",
        "candidate": "The device in the image is a refrigerator, which is covered with various pictures, magnets, and stickers, including a depiction of Mario and a car.",
        "reference": "fridge",
        "vote": 5,
    },
    {
        "question": "How many objects are on the wings of the plane pictured right?",
        "candidate": "no objects are on the wings of the plane pictured right",
        "reference": "8",
        "vote": 1,
    },
    {
        "question": "Is the skateboard in the air?",
        "candidate": "Yes, the skateboard is in the air, and the girl is sitting on the ground with her feet on the skateboard.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "Which part of this photo is in focus?",
        "candidate": "the boat",
        "reference": "foreground",
        "vote": 1,
    },
    {
        "question": "Which part of this photo is in focus?",
        "candidate": "The photo is in focus, with both the wooden boat and the smaller fishing boat in clear view.",
        "reference": "foreground",
        "vote": 1,
    },
    {
        "question": "How many people are shown?",
        "candidate": "There are two people shown in the image.",
        "reference": "2",
        "vote": 5,
    },
    {
        "question": "What time does the clock read?",
        "candidate": "The clock on the building reads 3:20.",
        "reference": "12:26",
        "vote": 1,
    },
    {
        "question": "What sport does this kid like?",
        "candidate": "The kid in the image likes the sport of baseball.",
        "reference": "baseball",
        "vote": 5,
    },
    {
        "question": "What color is her vest?",
        "candidate": "The woman in the image is wearing a black vest while skiing.",
        "reference": "black",
        "vote": 5,
    },
    {
        "question": "What color is the writing on the boy's shirt?",
        "candidate": "blue",
        "reference": "white",
        "vote": 1,
    },
    {
        "question": "What color is the writing on the boy's shirt?",
        "candidate": "The writing on the boy's shirt is blue.",
        "reference": "white",
        "vote": 1,
    },
    {
        "question": "Who do you think is enjoying the bench more?",
        "candidate": "Based on the image, it is difficult to determine with certainty who is enjoying the bench more, the man or the dog. However, it is clear that both the man and the dog are in a relaxed and comfortable position on",
        "reference": "man",
        "vote": 1,
    },
    {
        "question": "How many shelves are in the bookcase?",
        "candidate": "three",
        "reference": "2",
        "vote": 1,
    },
    {
        "question": "What shape is the orange fruit slice?",
        "candidate": "oblong",
        "reference": "circle",
        "vote": 1,
    },
    {
        "question": "Does it appear to be sunny out?",
        "candidate": "Yes, it appears to be a sunny day in the image.",
        "reference": "yes",
        "vote": 5,
    },
    {"question": "Could his back itch?", "candidate": "no", "reference": "yes", "vote": 1},
    {
        "question": "Could his back itch?",
        "candidate": "Yes, it is possible that the elephant's back itches. In the image, the elephant is standing in a grassy field next to a tree, and it appears to be rubbing its head on the tree trunk, which might indicate",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "How many white triangles are on the man's shirt?",
        "candidate": "four",
        "reference": "0",
        "vote": 1,
    },
    {
        "question": "Where is the woman sitting?",
        "candidate": "The woman is sitting on a bed.",
        "reference": "floor",
        "vote": 1,
    },
    {
        "question": "Where is the woman sitting?",
        "candidate": "in front of a mirror",
        "reference": "floor",
        "vote": 1,
    },
    {
        "question": "How many players are visible?",
        "candidate": "There are two players visible in the image.",
        "reference": "2",
        "vote": 5,
    },
    {
        "question": "Are the cat's eyes open?",
        "candidate": "Yes, the cat's eyes are open in the image.",
        "reference": "yes",
        "vote": 5,
    },
    {
        "question": "Is the elephant in the wild?",
        "candidate": "Yes, the elephant is in the wild, as it is seen walking around in a field with trees in the background.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "How many slices of pie are in the plate in the front of this picture?",
        "candidate": "There are two slices of pie on the plate in the front of the picture.",
        "reference": "1",
        "vote": 1,
    },
    {
        "question": "Is this a high-rise building?",
        "candidate": "Yes, the image shows a high-rise building, which is a tall structure with multiple floors.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "What color is the chair cushion?",
        "candidate": "The chair cushion in the image is red.",
        "reference": "red",
        "vote": 5,
    },
    {
        "question": "What season was this picture taken in?",
        "candidate": "autumn",
        "reference": "fall",
        "vote": 5,
    },
    {
        "question": "How many people are in this picture?",
        "candidate": "There are two people in the picture: a woman and a child.",
        "reference": "2",
        "vote": 5,
    },
    {
        "question": "What number is next to graham St?",
        "candidate": "3",
        "reference": "22",
        "vote": 1,
    },
    {
        "question": "What color is the plate?",
        "candidate": "The plate is white.",
        "reference": "white",
        "vote": 5,
    },
    {
        "question": "What movie are the characters depicted here from?",
        "candidate": "The characters depicted in the image are from the movie Star Wars.",
        "reference": "star wars",
        "vote": 5,
    },
    {
        "question": "How many elephants are here?",
        "candidate": "a couple of elephants",
        "reference": "1",
        "vote": 1,
    },
    {
        "question": "Is he wearing sunglasses?",
        "candidate": "Yes, the man is wearing sunglasses in the image.",
        "reference": "no",
        "vote": 1,
    },
    {
        "question": "How many deserts are there?",
        "candidate": "There are seven different types of donuts in the box.",
        "reference": "10",
        "vote": 1,
    },
    {"question": "How many deserts are there?", "candidate": "four", "reference": "10", "vote": 1},
    {
        "question": "How many sheep can be seen?",
        "candidate": "There are two sheep visible in the image.",
        "reference": "2",
        "vote": 5,
    },
    {
        "question": "How many people are wearing costumes?",
        "candidate": "a group of people",
        "reference": "2",
        "vote": 2,
    },
    {
        "question": "How many people are wearing costumes?",
        "candidate": "There is one person wearing a costume in the image.",
        "reference": "2",
        "vote": 1,
    },
    {
        "question": "What is on the people's head?",
        "candidate": "Both people are wearing helmets, with one person sitting on the motorcycle and the other person standing beside them.",
        "reference": "helmets",
        "vote": 5,
    },
    {
        "question": "What color is the horse?",
        "candidate": "The horse is brown in color.",
        "reference": "brown",
        "vote": 5,
    },
    {"question": "What color is the horse?", "candidate": "black", "reference": "brown", "vote": 1},
    {
        "question": "Are the bottles full or empty?",
        "candidate": "full",
        "reference": "empty",
        "vote": 1,
    },
    {
        "question": "How many plates are there?",
        "candidate": "There are four plates on the table.",
        "reference": "6",
        "vote": 1,
    },
]
