run:
    task: "classifier_vqa_followup"

    # old result folder with result/val_vqa_result.json will be set by calling script
    followup_prev_dir: none
    followup_cfg:
        model_name: "EVA01-g-14/laion400m_s11b_b41k"
        package_name: "open-clip"

        # matching predictions to classes, to find wrong answers
        use_synonyms_leaves: false
        templates_name_leaves: "none"
        arg_max_or_average_syn_leaves: "arg_max_syn"

        # matching predictions to parents, to find next question object
        use_synonyms_parents: true
        templates_name_parents: "none"
        arg_max_or_average_syn_parents: "arg_max_syn"

        threshold: 0.37
        # followup_prompt: none  # will be set by model config
        default_followup_object: "activity"
        cut_long_text: true
        exclude_parents: ["0"]  # root/activity
