# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
    arch: "blip2_opt"
    model_type: "pretrain_opt2.7b"
    use_grad_checkpoint: False

datasets:
    imagenet1k:
        question_type: "what-seen-image"
        type: "eval"
        vis_processor:
            eval:
                name: "blip_image_eval"
                image_size: 224
        text_processor:
            eval:
                name: "blip_question"

run:
    task: "classifier_vqa"
    batch_size_train: 16
    batch_size_eval: 16
    num_workers: 4

    max_new_tokens: 10
    min_new_tokens: 1
    length_penalty: -1.0  # 1.0: no penalty, -1.0: very short answers
    num_beams: 5
    inference_method: "generate"
    prompt: "Question: {} Short answer:"
    followup_cfg:
        followup_prompt: "Question: What type of {} is this? Short answer:"

    seed: 42
    output_dir_add_job_id: False
    evaluate: True
    test_splits: [ "val" ]

    device: "cuda"
    world_size: 1
    dist_url: "env://"
    distributed: True
