# adapted and modified from https://github.com/lvis-dataset/lvis-api/blob/master/data/coco_to_synset.json
# License: see https://github.com/lvis-dataset/lvis-api/blob/master/LICENSE
# and https://github.com/facebookresearch/detectron2/blob/main/detectron2/data/datasets/lvis_v1_categories.py
# License: Apache-2.0 License

COCO_OBJ_CLS = {
    "bench": {
        "coco_cat_id": 15,
        "meaning": "a long seat for more than one person",
        "synset": "bench.n.01",
        "synonyms": ["bench"],
        "name": "bench",
        "plural": "benches",
    },
    "baseball bat": {
        "coco_cat_id": 39,
        "meaning": "an implement used in baseball by the batter",
        "synset": "baseball_bat.n.01",
        "synonyms": ["baseball bat"],
        "name": "baseball bat",
        "plural": "baseball bats",
    },
    "kite": {
        "coco_cat_id": 38,
        "meaning": "plaything consisting of a light frame covered with tissue paper; flown in wind at end of a string",
        "synset": "kite.n.03",
        "synonyms": ["kite"],
        "name": "kite",
        "plural": "kites",
    },
    "orange": {
        "coco_cat_id": 55,
        "meaning": "orange (FRUIT of an orange tree)",
        "synset": "orange.n.01",
        "synonyms": ["orange", "orange (fruit)"],
        "name": "orange",
        "plural": "oranges",
    },
    "boat": {
        "coco_cat_id": 9,
        "meaning": "a vessel for travel on water",
        "synset": "boat.n.01",
        "synonyms": ["boat", "ship (boat)"],
        "name": "boat",
        "plural": "boats",
    },
    "carrot": {
        "coco_cat_id": 57,
        "meaning": "deep orange edible root of the cultivated carrot plant",
        "synset": "carrot.n.01",
        "synonyms": ["carrot", "carrot (vegetable)"],
        "name": "carrot",
        "plural": "carrots",
    },
    "bicycle": {
        "coco_cat_id": 2,
        "meaning": "a wheeled vehicle that has two wheels and is moved by foot pedals",
        "synset": "bicycle.n.01",
        "synonyms": ["bicycle", "bike (bicycle)", "bike"],
        "name": "bicycle",
        "plural": "bicycles",
    },
    "book": {
        "coco_cat_id": 84,
        "meaning": "a written work or composition that has been published",
        "synset": "book.n.01",
        "synonyms": ["book"],
        "name": "book",
        "plural": "books",
    },
    "toothbrush": {
        "coco_cat_id": 90,
        "meaning": "small brush; has long handle; used to clean teeth",
        "synset": "toothbrush.n.01",
        "synonyms": ["toothbrush"],
        "name": "toothbrush",
        "plural": "toothbrushes",
    },
    "tie": {
        "coco_cat_id": 32,
        "meaning": "neckwear consisting of a long narrow piece of material worn under a collar and tied in knot at the front",
        "synset": "necktie.n.01",
        "synonyms": ["tie", "necktie", "tie (necktie)"],
        "name": "tie",
        "plural": "ties",
    },
    "sandwich": {
        "coco_cat_id": 54,
        "meaning": "two (or more) slices of bread with a filling between them",
        "synset": "sandwich.n.01",
        "synonyms": ["sandwich"],
        "name": "sandwich",
        "plural": "sandwiches",
    },
    "toilet": {
        "coco_cat_id": 70,
        "meaning": "a plumbing fixture for defecation and urination",
        "synset": "toilet.n.02",
        "synonyms": ["toilet", "toilette"],
        "name": "toilet",
        "plural": "toilets",
    },
    "stop sign": {
        "coco_cat_id": 13,
        "meaning": "a traffic sign to notify drivers that they must come to a complete stop",
        "synset": "stop_sign.n.01",
        "synonyms": ["stop sign"],
        "name": "stop sign",
        "plural": "stop signs",
    },
    "wine glass": {
        "coco_cat_id": 46,
        "meaning": "a glass that has a stem and in which wine is served",
        "synset": "wineglass.n.01",
        "synonyms": ["wine glass", "wineglass"],
        "name": "wine glass",
        "plural": "wine glasses",
    },
    "clock": {
        "coco_cat_id": 85,
        "meaning": "a timepiece that shows the time of day",
        "synset": "clock.n.01",
        "synonyms": ["clock", "timekeeper", "timepiece", "watch (clock)", "wristwatch"],
        "name": "clock",
        "plural": "clocks",
    },
    "bear": {
        "coco_cat_id": 23,
        "meaning": "large carnivorous or omnivorous mammals with shaggy coats and claws",
        "synset": "bear.n.01",
        "synonyms": ["bear"],
        "name": "bear",
        "plural": "bears",
    },
    "vase": {
        "coco_cat_id": 86,
        "meaning": "an open jar of glass or porcelain used as an ornament or to hold flowers",
        "synset": "vase.n.01",
        "synonyms": ["vase"],
        "name": "vase",
        "plural": "vases",
    },
    "microwave": {
        "coco_cat_id": 78,
        "meaning": "kitchen appliance that cooks food by passing an electromagnetic wave through it",
        "synset": "microwave.n.02",
        "synonyms": ["microwave", "microwave oven"],
        "name": "microwave",
        "plural": "microwaves",
    },
    "oven": {
        "coco_cat_id": 79,
        "meaning": "kitchen appliance used for baking or roasting",
        "synset": "oven.n.01",
        "synonyms": ["oven"],
        "name": "oven",
        "plural": "ovens",
    },
    "cake": {
        "coco_cat_id": 61,
        "meaning": "baked goods made from or based on a mixture of flour, sugar, eggs, and fat",
        "synset": "cake.n.03",
        "synonyms": ["cake"],
        "name": "cake",
        "plural": "cakes",
    },
    "apple": {
        "coco_cat_id": 53,
        "meaning": "fruit with red or yellow or green skin and sweet to tart crisp whitish flesh",
        "synset": "apple.n.01",
        "synonyms": ["apple", "apple (fruit)"],
        "name": "apple",
        "plural": "apples",
    },
    "bed": {
        "coco_cat_id": 65,
        "meaning": "a piece of furniture that provides a place to sleep",
        "synset": "bed.n.01",
        "synonyms": ["bed"],
        "name": "bed",
        "plural": "beds",
    },
    "skis": {
        "coco_cat_id": 35,
        "meaning": "sports equipment for skiing on snow",
        "synset": "ski.n.01",
        "synonyms": ["skis", "ski"],
        "name": "skis",
        "plural": "skis",
    },
    "dining table": {
        "coco_cat_id": 67,
        "meaning": "a table at which meals are served",
        "synset": "dining_table.n.01",
        "synonyms": ["dining table"],
        "name": "dining table",
        "plural": "dining tables",
    },
    "remote": {
        "coco_cat_id": 75,
        "meaning": "a device that can be used to control a machine or apparatus from a distance",
        "synset": "remote_control.n.01",
        "synonyms": ["remote", "remote control"],
        "name": "remote",
        "plural": "remotes",
    },
    "bird": {
        "coco_cat_id": 16,
        "meaning": "animal characterized by feathers and wings",
        "synset": "bird.n.01",
        "synonyms": ["bird"],
        "name": "bird",
        "plural": "birds",
    },
    "laptop": {
        "coco_cat_id": 73,
        "meaning": "a portable computer small enough to use in your lap",
        "synset": "laptop.n.01",
        "synonyms": ["laptop", "notebook computer", "laptop computer"],
        "name": "laptop",
        "plural": "laptops",
    },
    "train": {
        "coco_cat_id": 7,
        "meaning": "public or private transport provided by a line of railway cars coupled together and drawn by a locomotive",
        "synset": "train.n.01",
        "synonyms": ["train", "railroad train", "train (railroad vehicle)"],
        "name": "train",
        "plural": "trains",
    },
    "mouse": {
        "coco_cat_id": 74,
        "meaning": "a computer input device that controls an on-screen pointer",
        "synset": "mouse.n.04",
        "synonyms": ["mouse", "computer mouse", "mouse (computer equipment)"],
        "name": "mouse",
        "plural": "mice",
    },
    "pizza": {
        "coco_cat_id": 59,
        "meaning": "Italian open pie made of thin bread dough spread with a spiced mixture of e.g. tomato sauce and cheese",
        "synset": "pizza.n.01",
        "synonyms": ["pizza"],
        "name": "pizza",
        "plural": "pizzas",
    },
    "toaster": {
        "coco_cat_id": 80,
        "meaning": "a kitchen appliance (usually electric) for toasting bread",
        "synset": "toaster.n.02",
        "synonyms": ["toaster"],
        "name": "toaster",
        "plural": "toasters",
    },
    "cell phone": {
        "coco_cat_id": 77,
        "meaning": "a hand-held mobile telephone",
        "synset": "cellular_telephone.n.01",
        "synonyms": [
            "cell phone",
            "cellphone",
            "cellular telephone",
            "cellular phone",
            "mobile phone",
            "smart phone",
        ],
        "name": "cell phone",
        "plural": "cell phones",
    },
    "person": {
        "coco_cat_id": 1,
        "meaning": "a human being",
        "synset": "person.n.01",
        "synonyms": [
            "person",
            "boy",
            "girl",
            "man",
            "human",
            "child",
            "baby",
            "woman",
            "people",
            "men",
            "women",
            "player",
        ],
        "name": "person",
        "plural": "people",
    },
    "sports ball": {
        "coco_cat_id": 37,
        "meaning": "a spherical object used as a plaything",
        "synset": "ball.n.06",
        "synonyms": ["sports ball", "ball"],
        "name": "sports ball",
        "plural": "sports balls",
    },
    "fire hydrant": {
        "coco_cat_id": 11,
        "meaning": "an upright hydrant for drawing water to use in fighting a fire",
        "synset": "fireplug.n.01",
        "synonyms": ["fire hydrant", "hydrant", "fireplug"],
        "name": "fire hydrant",
        "plural": "fire hydrants",
    },
    "umbrella": {
        "coco_cat_id": 28,
        "meaning": "a lightweight handheld collapsible canopy",
        "synset": "umbrella.n.01",
        "synonyms": ["umbrella"],
        "name": "umbrella",
        "plural": "umbrellas",
    },
    "truck": {
        "coco_cat_id": 8,
        "meaning": "an automotive vehicle suitable for hauling",
        "synset": "truck.n.01",
        "synonyms": ["truck"],
        "name": "truck",
        "plural": "trucks",
    },
    "knife": {
        "coco_cat_id": 49,
        "meaning": "tool with a blade and point used as a cutting instrument",
        "synset": "knife.n.01",
        "synonyms": ["knife"],
        "name": "knife",
        "plural": "knives",
    },
    "baseball glove": {
        "coco_cat_id": 40,
        "meaning": "the handwear used by fielders in playing baseball",
        "synset": "baseball_glove.n.01",
        "synonyms": ["baseball glove", "baseball mitt"],
        "name": "baseball glove",
        "plural": "baseball gloves",
    },
    "giraffe": {
        "coco_cat_id": 25,
        "meaning": "tall animal having a spotted coat and small horns and very long neck and legs",
        "synset": "giraffe.n.01",
        "synonyms": ["giraffe"],
        "name": "giraffe",
        "plural": "giraffes",
    },
    "airplane": {
        "coco_cat_id": 5,
        "meaning": "an aircraft that has a fixed wing and is powered by propellers or jets",
        "synset": "airplane.n.01",
        "synonyms": ["airplane", "aeroplane"],
        "name": "airplane",
        "plural": "airplanes",
    },
    "parking meter": {
        "coco_cat_id": 14,
        "meaning": "a coin-operated timer located next to a parking space",
        "synset": "parking_meter.n.01",
        "synonyms": ["parking meter"],
        "name": "parking meter",
        "plural": "parking meters",
    },
    "couch": {
        "coco_cat_id": 63,
        "meaning": "an upholstered seat for more than one person",
        "synset": "sofa.n.01",
        "synonyms": ["couch", "lounge", "sofa"],
        "name": "couch",
        "plural": "couches",
    },
    "tennis racket": {
        "coco_cat_id": 43,
        "meaning": "a racket used to play tennis",
        "synset": "tennis_racket.n.01",
        "synonyms": ["tennis racket"],
        "name": "tennis racket",
        "plural": "tennis rackets",
    },
    "backpack": {
        "coco_cat_id": 27,
        "meaning": "a bag carried by a strap on your back or shoulder",
        "synset": "backpack.n.01",
        "synonyms": ["backpack", "knapsack", "packsack", "haversack", "rucksack"],
        "name": "backpack",
        "plural": "backpacks",
    },
    "hot dog": {
        "coco_cat_id": 58,
        "meaning": "a smooth-textured sausage, usually smoked, often served on a bread roll",
        "synset": "frank.n.02",
        "synonyms": ["hot dog"],
        "name": "hot dog",
        "plural": "hot dogs",
    },
    "banana": {
        "coco_cat_id": 52,
        "meaning": "elongated crescent-shaped yellow fruit with soft sweet flesh",
        "synset": "banana.n.02",
        "synonyms": ["banana", "banana (fruit)"],
        "name": "banana",
        "plural": "bananas",
    },
    "bowl": {
        "coco_cat_id": 51,
        "meaning": "a dish that is round and open at the top for serving foods",
        "synset": "bowl.n.03",
        "synonyms": ["bowl"],
        "name": "bowl",
        "plural": "bowls",
    },
    "skateboard": {
        "coco_cat_id": 41,
        "meaning": "a board with wheels that is ridden in a standing or crouching position and propelled by foot",
        "synset": "skateboard.n.01",
        "synonyms": ["skateboard"],
        "name": "skateboard",
        "plural": "skateboards",
    },
    "bottle": {
        "coco_cat_id": 44,
        "meaning": "a glass or plastic vessel used for storing drinks or other liquids",
        "synset": "bottle.n.01",
        "synonyms": ["bottle"],
        "name": "bottle",
        "plural": "bottles",
    },
    "dog": {
        "coco_cat_id": 18,
        "meaning": "a common domesticated dog",
        "synset": "dog.n.01",
        "synonyms": ["dog", "puppy"],
        "name": "dog",
        "plural": "dogs",
    },
    "frisbee": {
        "coco_cat_id": 34,
        "meaning": "a light, plastic disk propelled with a flip of the wrist for recreation or competition",
        "synset": "frisbee.n.01",
        "synonyms": ["frisbee"],
        "name": "frisbee",
        "plural": "frisbees",
    },
    "broccoli": {
        "coco_cat_id": 56,
        "meaning": "plant with dense clusters of tight green flower buds",
        "synset": "broccoli.n.01",
        "synonyms": ["broccoli", "broccoli (vegetable)"],
        "name": "broccoli",
        "plural": "broccoli",
    },
    "elephant": {
        "coco_cat_id": 22,
        "meaning": "a common elephant",
        "synset": "elephant.n.01",
        "synonyms": ["elephant"],
        "name": "elephant",
        "plural": "elephants",
    },
    "car": {
        "coco_cat_id": 3,
        "meaning": "a motor vehicle with four wheels",
        "synset": "car.n.01",
        "synonyms": ["car", "car (automobile)", "automobile", "auto (automobile)"],
        "name": "car",
        "plural": "cars",
    },
    "donut": {
        "coco_cat_id": 60,
        "meaning": "a small ring-shaped friedcake",
        "synset": "doughnut.n.02",
        "synonyms": ["donut", "doughnut"],
        "name": "donut",
        "plural": "donuts",
    },
    "suitcase": {
        "coco_cat_id": 33,
        "meaning": "cases used to carry belongings when traveling",
        "synset": "bag.n.06",
        "synonyms": ["suitcase", "luggage", "baggage"],
        "name": "suitcase",
        "plural": "suitcases",
    },
    "cup": {
        "coco_cat_id": 47,
        "meaning": "a small open container usually used for drinking; usually has a handle",
        "synset": "cup.n.01",
        "synonyms": ["cup"],
        "name": "cup",
        "plural": "cups",
    },
    "hair drier": {
        "coco_cat_id": 89,
        "meaning": "a hand-held electric blower that can blow warm air onto the hair",
        "synset": "hand_blower.n.01",
        "synonyms": ["hair drier", "hair dryer"],
        "name": "hair drier",
        "plural": "hair driers",
    },
    "surfboard": {
        "coco_cat_id": 42,
        "meaning": "a narrow buoyant board for riding surf",
        "synset": "surfboard.n.01",
        "synonyms": ["surfboard"],
        "name": "surfboard",
        "plural": "surfboards",
    },
    "traffic light": {
        "coco_cat_id": 10,
        "meaning": "a device to control vehicle traffic often consisting of three or more lights",
        "synset": "traffic_light.n.01",
        "synonyms": ["traffic light"],
        "name": "traffic light",
        "plural": "traffic lights",
    },
    "tv": {
        "coco_cat_id": 72,
        "meaning": "an electronic device that receives television signals and displays them on a screen",
        "synset": "television_receiver.n.01",
        "synonyms": ["tv", "television set", "tv set"],
        "name": "tv",
        "plural": "tv sets",
    },
    "spoon": {
        "coco_cat_id": 50,
        "meaning": "a piece of cutlery with a shallow bowl-shaped container and a handle",
        "synset": "spoon.n.01",
        "synonyms": ["spoon"],
        "name": "spoon",
        "plural": "spoons",
    },
    "horse": {
        "coco_cat_id": 19,
        "meaning": "a common horse",
        "synset": "horse.n.01",
        "synonyms": ["horse"],
        "name": "horse",
        "plural": "horses",
    },
    "motorcycle": {
        "coco_cat_id": 4,
        "meaning": "a motor vehicle with two wheels and a strong frame",
        "synset": "motorcycle.n.01",
        "synonyms": ["motorcycle"],
        "name": "motorcycle",
        "plural": "motorcycles",
    },
    "zebra": {
        "coco_cat_id": 24,
        "meaning": "any of several fleet black-and-white striped African equines",
        "synset": "zebra.n.01",
        "synonyms": ["zebra"],
        "name": "zebra",
        "plural": "zebras",
    },
    "cat": {
        "coco_cat_id": 17,
        "meaning": "a domestic house cat",
        "synset": "cat.n.01",
        "synonyms": ["cat"],
        "name": "cat",
        "plural": "cats",
    },
    "teddy bear": {
        "coco_cat_id": 88,
        "meaning": "plaything consisting of a child's toy bear (usually plush and stuffed with soft materials)",
        "synset": "teddy.n.01",
        "synonyms": ["teddy bear"],
        "name": "teddy bear",
        "plural": "teddy bears",
    },
    "handbag": {
        "coco_cat_id": 31,
        "meaning": "a container used for carrying money and small personal items or accessories",
        "synset": "bag.n.04",
        "synonyms": ["handbag", "pocketbook", "purse"],
        "name": "handbag",
        "plural": "handbags",
    },
    "sink": {
        "coco_cat_id": 81,
        "meaning": "plumbing fixture consisting of a water basin fixed to a wall or floor and having a drainpipe",
        "synset": "sink.n.01",
        "synonyms": ["sink"],
        "name": "sink",
        "plural": "sinks",
    },
    "keyboard": {
        "coco_cat_id": 76,
        "meaning": "a keyboard that is a data input device for computers",
        "synset": "computer_keyboard.n.01",
        "synonyms": ["keyboard", "computer keyboard", "keyboard (computer)"],
        "name": "keyboard",
        "plural": "keyboards",
    },
    "bus": {
        "coco_cat_id": 6,
        "meaning": "a vehicle carrying many passengers; used for public transport",
        "synset": "bus.n.01",
        "synonyms": [
            "bus",
            "charabanc",
            "double-decker",
            "bus (vehicle)",
            "motorcoach",
            "autobus",
            "motorbus",
        ],
        "name": "bus",
        "plural": "buses",
    },
    "fork": {
        "coco_cat_id": 48,
        "meaning": "cutlery used for serving and eating food",
        "synset": "fork.n.01",
        "synonyms": ["fork"],
        "name": "fork",
        "plural": "forks",
    },
    "chair": {
        "coco_cat_id": 62,
        "meaning": "a seat for one person, with a support for the back",
        "synset": "chair.n.01",
        "synonyms": ["chair"],
        "name": "chair",
        "plural": "chairs",
    },
    "refrigerator": {
        "coco_cat_id": 82,
        "meaning": "a refrigerator in which the coolant is pumped around by an electric motor",
        "synset": "electric_refrigerator.n.01",
        "synonyms": ["refrigerator"],
        "name": "refrigerator",
        "plural": "refrigerators",
    },
    "scissors": {
        "coco_cat_id": 87,
        "meaning": "a tool having two crossed pivoting blades with looped handles",
        "synset": "scissors.n.01",
        "synonyms": ["scissors"],
        "name": "scissors",
        "plural": "scissors",
    },
    "sheep": {
        "coco_cat_id": 20,
        "meaning": "woolly usually horned ruminant mammal related to the goat",
        "synset": "sheep.n.01",
        "synonyms": ["sheep"],
        "name": "sheep",
        "plural": "sheep",
    },
    "potted plant": {
        "coco_cat_id": 64,
        "meaning": "a container in which plants are cultivated",
        "synset": "pot.n.04",
        "synonyms": ["potted plant", "flowerpot", "flower pot"],
        "name": "potted plant",
        "plural": "potted plants",
    },
    "snowboard": {
        "coco_cat_id": 36,
        "meaning": "a board that resembles a broad ski or a small surfboard; used in a standing position to slide down snow-covered slopes",
        "synset": "snowboard.n.01",
        "synonyms": ["snowboard"],
        "name": "snowboard",
        "plural": "snowboards",
    },
    "cow": {
        "coco_cat_id": 21,
        "meaning": "cattle that are reared for their meat",
        "synset": "beef.n.01",
        "synonyms": ["cow"],
        "name": "cow",
        "plural": "cows",
    },
}
